# nginx proxy address - http://172.17.0.1:8083

name: calibre-web
x-logging: &default-logging
  driver: json-file
  options:
    max-size: "5m"
    max-file: "1"

services:
  app:
    image: linuxserver/calibre-web:latest
    pull_policy: always
    container_name: calibre-web-app
    hostname: ${BASE_HOST_NAME:-$HOSTNAME}
    restart: always
    logging: *default-logging
    networks:
      - calibre-web
      - proxy
      - cloudflare
    ports:
      - "172.17.0.1:8083:8083"
    environment:
      TZ: ${TZ:-America/New_York}
      PUID: ${SERVICE_USER:-1000}
      PGID: ${SERVICE_GROUP:-1000}
      DOCKER_MODS: linuxserver/mods:universal-calibre
      CONTAINER_NAME: calibre-web-app
      HOSTNAME: ${BASE_HOST_NAME:-$HOSTNAME}
    volumes:
      - ./volumes/config/calibre-web:/config
      - ./volumes/data/calibre-web:/books
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8083"]
      interval: 30s
      timeout: 10s
      retries: 3
    labels:
      - 'traefik.enable=true'
      - 'cloudflare.enable=true'
      - 'traefik.docker.network=proxy'
      - 'cloudflare.service=http://calibre-web-app:8083'
      - 'cloudflare.hostname=calibre-web.${CLOUDFLARE_ZONE_NAME:-}'
      - 'traefik.http.routers.calibre-web-app.entrypoints=http'
      - 'traefik.http.routers.calibre-web-app-secure.tls=true'
      - 'traefik.http.routers.calibre-web-app.rule=Host($(${BASE_HOST_NAME:-$HOSTNAME}))'
      - 'traefik.http.middlewares.calibre-web-app-https-redirect.redirectscheme.scheme=https'
      - 'traefik.http.routers.calibre-web-app.middlewares=calibre-web-app-https-redirect'
      - 'traefik.http.routers.calibre-web-app-secure.entrypoints=https'
      - 'traefik.http.routers.calibre-web-app-secure.rule=Host($(${BASE_HOST_NAME:-$HOSTNAME}))'
      - 'traefik.http.routers.calibre-web-app-secure.tls.certresolver=cloudflare'
      - 'traefik.http.routers.calibre-web-app-secure.service=calibre-web-app'
      - 'traefik.http.services.calibre-web-app.loadbalancer.server.port=8083'

networks:
  calibre-web:
    name: calibre-web
    external: false
  proxy:
    external: true
  cloudflare:
    external: true
