# nginx proxy address - http://172.17.0.1:8083

name: calibre-web
x-logging: &default-logging
  driver: json-file
  options:
    max-size: "5m"
    max-file: "1"

services:
  app:
    image: linuxserver/calibre-web:latest
    pull_policy: always
    container_name: calibre-web-app
    hostname: ${BASE_HOST_NAME:-$HOSTNAME}
    restart: always
    logging: *default-logging
    networks:
      - calibre-web
    ports:
      - "172.17.0.1:8083:8083"
    environment:
      TZ: ${TZ:-America/New_York}
      PUID: ${SERVICE_USER:-1000}
      PGID: ${SERVICE_GROUP:-1000}
      DOCKER_MODS: linuxserver/mods:universal-calibre
    volumes:
      - ./volumes/config/calibre-web:/config
      - ./volumes/data/calibre-web:/books
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8083"]
      interval: 30s
      timeout: 10s
      retries: 3

networks:
  calibre-web:
    name: calibre-web
    external: false
